---
title: "Trees with multiple visits per cycle"
format: gfm
---

```{r, echo = F, message = F, warning = F}

library(duckdb)
library(dplyr)

source(here::here("R", "query_tables_db_fxns.R"))

fips <- read.csv(here::here("data", "rawdat", "fips", "fips.csv"))

con <- connect_to_tables(here::here("data", "db", "forestTIME-cli.duckdb"))
```

```{r}

trees_last_sp <- tbl(con, "tree_raw") |>
  select(TREE_UNIQUE_ID, INVYR, SPCD) |>
  group_by(TREE_UNIQUE_ID) |>
  mutate(last_invyr = max(INVYR)) |>
  ungroup() |>
  filter(INVYR == last_invyr) |>
  rename(SPCD_LAST = SPCD) |>
  select(TREE_UNIQUE_ID, SPCD_LAST) 

tree_info_last_sp <- tbl(con, "tree_info_composite_id") |>
  left_join(trees_last_sp) |>
  mutate(SPCD_FLAG = SPCD != SPCD_LAST) |>
  collect()

arrow::to_duckdb(tree_info_last_sp, table_name = "tree_info_composite_id_corr", con = con)
dbSendQuery(con, "CREATE TABLE tree_info_composite_id_corr AS SELECT * FROM tree_info_composite_id_corr")

```


```{r, echo = F, message = F, output = F}

dbDisconnect(con, shutdown = TRUE)

```