---
title: "Extracting FIA timeseries"
format: gfm
editor: source
---

```{r}
#| echo: FALSE
#| message: FALSE
#| warning: FALSE

library(duckdbfs)
library(dplyr)
library(ggplot2)

source(here::here("R", "flexible_filtering_functions.R"))

```

## 1. `select_trees`

`select_trees()` extracts persistent IDs for all trees that meet user-supplied criteria.

By default, `select_trees` returns all trees:

```{r}

my_trees <- select_trees_list(connection = "local")

nrow(my_trees)

knitr::kable(head(my_trees))

```

Passing additional options filters the trees:

```{r}

# Extract all red maples (SPCD = 316)

my_red_maples <- select_trees_list(condition_list = list(
  SPCD = list("==", 316)
))

nrow(my_red_maples)

knitr::kable(head(my_red_maples))

```

```{r}

# Extract red maples on plot 27_3_65_20067

my_red_maples_one_plot <- select_trees_list(condition_list = list(
  SPCD = list("==", 316),
  PLOT_UNIQUE_ID = list("==", "27_3_65_20067")))

nrow(my_red_maples_one_plot)

knitr::kable(head(my_red_maples_one_plot))

```

```{r}

my_red_maples_one_county <- select_trees_list(list(
  SPCD = list("==", 316),
  STATECD = list("==", 27),
  COUNTYCD = list("==", 65)
))

nrow(my_red_maples_one_county)

knitr::kable(head(my_red_maples_one_county))

```

## 2. `get_timeseries`


```{r}

my_maple_timeseries <- filter_on_passed_vars(my_red_maples_one_county, connection = 'local')

nrow(my_maple_timeseries)

knitr::kable(head(my_maple_timeseries))
```



Modifying the time window and variables to return:


```{r}

my_maple_timeseries2 <- filter_on_passed_vars(my_red_maples_one_plot, 
                                       conditions = list(STATUSCD = list("==", 1),
                                                         INVYR = list("%in%", 2005:2024),
                                                         CONDID = list("==", 2)),
                                       variables = c("DIA", "HT", "ACTUALHT", "CONDID"),
                                       connection = "local")

nrow(my_maple_timeseries2)

knitr::kable(head(my_maple_timeseries2))
```

Here is a plot of how individual maple trees' diameters have changed over time:

```{r}
#| label: fig-mapledia
#| fig-cap: Diameters of red maple trees on plot 20010 over time. Individual lines represent individual trees.
#| echo: false

ggplot(my_maple_timeseries2, aes(INVYR, DIA, group = as.factor(TREE_UNIQUE_ID))) +
  geom_line() +
  geom_point() +
  theme_bw() +
  ggtitle("Maple tree diameters over time", subtitle = "Plot 27_3_65_20067") +
  xlab("INVYR") +
  ylab("DIA")

```

