---
title: "Tables (currently)"
format: 
  gfm:
    toc: true
editor: source
---

```{r}

source(here::here("R", "filtering.R"))
library(duckdbfs)
library(duckdb)
library(ggplot2)
library(dplyr)

```

## PLOT_INFO

```{r}

plot_info <- open_arrow_table_with_duck("PLOT_INFO") |>
  filter(PLOT_UNIQUE_ID %in% c("27_2_1_20400", "27_2_1_21053", "27_2_1_21054", "27_2_1_21055", "27_2_1_20206", "27_2_1_21007", "27_2_1_20829", "27_2_1_20401", "27_2_1_20667", "27_2_1_20943")) |>
  collect()

knitr::kable(plot_info)

```

## TREE_INFO


```{r}

tree_info <- open_arrow_table_with_duck("TREE_INFO") |>
  filter(PLOT_UNIQUE_ID %in% c("27_2_1_20400", "27_2_1_21053", "27_2_1_21054", "27_2_1_21055", "27_2_1_20206", "27_2_1_21007", "27_2_1_20829", "27_2_1_20401", "27_2_1_20667", "27_2_1_20943")) |>
  collect()

knitr::kable(head(tree_info))

```

## PLOT


```{r}

plot_raw <- open_arrow_table_with_duck(table = "PLOT") |>
  filter(PLOT_UNIQUE_ID %in% c("27_2_1_20400", "27_2_1_21053", "27_2_1_21054", "27_2_1_21055", "27_2_1_20206", "27_2_1_21007", "27_2_1_20829", "27_2_1_20401", "27_2_1_20667", "27_2_1_20943")) |>
  collect()

knitr::kable(head(plot_raw))

```

## TREE


```{r}

tree_raw <- open_arrow_table_with_duck("TREE") |>
  filter(PLOT_UNIQUE_ID %in% c("27_2_1_20400", "27_2_1_21053", "27_2_1_21054", "27_2_1_21055", "27_2_1_20206", "27_2_1_21007", "27_2_1_20829", "27_2_1_20401", "27_2_1_20667", "27_2_1_20943")) |>
  collect()

knitr::kable(head(tree_raw))

```

