---
title: "Pulling timeseries of surveys"
format: gfm
editor: source
---

```{r}

source(here::here("R", "query_tables_db_fxns.R"))

con <- connect_to_tables(here::here("data", "db", "derived_tables3.duckdb"))

```

Here's an unmodified query for whitebark pine in MT:

```{r}


wb_pine_raw <- query_tree_surveys(
  con,
  conditions = create_conditions(STATECD == 30,
                                 SPCD == 101),
  variables = c(
    "STATUSCD",
    "DIA",
    "HT",
    "COND_STATUS_CD",
    "LAT",
    "LON",
    "BALIVE",
    "SICOND",
    "SISP",
    "SIBASE",
    "DSTRBCD1",
    "DSTRBYR1",
    "DSTRBCD2",
    "DSTRBYR2",
    "DSTRBCD3",
    "DSTRBYR3",
    "SDIMAX_RMRS",
    "SDI_RMRS",
    "SLOPE",
    "ASPECT",
    "CONDPROP_UNADJ",
    "RECONCILECD"
  )
)

```

```{r}



qa_d_wb_pine <- query_tree_surveys(
  con = con,
  conditions = create_conditions(
    STATECD == 30,
    SPCD == 101,
    ANY_SPCD_FLAG == FALSE
  ),
  variables = c(
    "STATUSCD",
    "STATUSCD_CORR",
    "STATUSCD_FLAG",
    "DIA",
    "HT",
    "COND_STATUS_CD",
    "LAT",
    "LON",
    "BALIVE",
    "SICOND",
    "SISP",
    "SIBASE",
    "DSTRBCD1",
    "DSTRBYR1",
    "DSTRBCD2",
    "DSTRBYR2",
    "DSTRBCD3",
    "DSTRBYR3",
    "SDIMAX_RMRS",
    "SDI_RMRS",
    "SLOPE",
    "ASPECT",
    "CONDPROP_UNADJ",
    "RECONCILECD"
  )
)

```

```{r}

dbDisconnect(con, shutdown = TRUE)

```